Repository octopusden/octopus-components-registry-service, pull requests merged in 2024-09, with the labels that each got.

#52 Actualize RM Docker Guideline
  docs/configuration.adoc
Labels: documentation

#53 update com.avast.gradle.docker-compose to 0.17.8 to fix the build
  build.gradle
Labels: build

#55 External registry resolved to null in case of version range
  component-resolver-core/src/main/groovy/org.octopusden/octopus/escrow/configuration/loader/EscrowConfigurationLoader.groovy
  component-resolver-core/src/test/groovy/org/octopusden/octopus/escrow/resolvers/RepositoryResolverTest.groovy
  component-resolver-core/src/test/resources/new-vcs/externalRegistryWithVersionRange.groovy
Labels: bug

#56 JiraComponentVersion with clean ComponentVersion (w/o prefix)
  components-registry-service-core/src/main/kotlin/org/octopusden/octopus/components/registry/core/dto/DetailedComponent.kt
  components-registry-service-core/src/main/kotlin/org/octopusden/octopus/components/registry/core/dto/DetailedComponentVersion.kt
  components-registry-service-server/src/main/kotlin/org/octopusden/octopus/components/registry/server/controller/ComponentControllerV2.kt
  components-registry-service-server/src/main/kotlin/org/octopusden/octopus/components/registry/server/mapper/JiraComponentVersionToDetailedComponentVersionMapper.kt
  components-registry-service-server/src/main/kotlin/org/octopusden/octopus/components/registry/server/service/impl/ComponentRegistryResolverImpl.kt
  test-common/src/test/resources/expected-data/versions-api-version-api.1.0-jira-component-version.json
  test-common/src/testFixtures/kotlin/org/octopusden/octopus/components/registry/test/BaseComponentsRegistryServiceTest.kt
Labels: enhancement
