Repository octopusden/octopus-components-registry-service, pull requests merged in 2025-06, with the labels that each got.

#90 Support RC version and temporary remove hotfix version support in version normalization
  component-resolver-core/src/main/groovy/org.octopusden/octopus/escrow/configuration/loader/EscrowConfigurationLoader.groovy
  test-common/src/testFixtures/kotlin/org/octopusden/octopus/components/registry/test/BaseComponentsRegistryServiceTest.kt
Labels: bug

#91 Add jira RC version in tests
  components-registry-service-server/src/main/kotlin/org/octopusden/octopus/components/registry/server/service/impl/ComponentRegistryResolverImpl.kt
  test-common/src/test/resources/expected-data/sub-hlk-1.0_RC-vcs-settings.json
  test-common/src/testFixtures/kotlin/org/octopusden/octopus/components/registry/test/BaseComponentsRegistryServiceTest.kt
Labels: build

#92 clean up support of an obsolete version in docker #88
  component-resolver-core/src/main/groovy/org.octopusden/octopus/escrow/configuration/loader/EscrowConfigurationLoader.groovy
  component-resolver-core/src/main/groovy/org.octopusden/octopus/escrow/configuration/validation/GroovySlurperConfigValidator.groovy
  component-resolver-core/src/test/groovy/org/octopusden/octopus/escrow/configuration/validation/GroovySlurperConfigValidatorTest.groovy
  component-resolver-core/src/test/resources/distribution-docker/InfrastructureComponents.groovy
  component-resolver-core/src/test/resources/distributionsInRangesDocker.groovy
  component-resolver-core/src/test/resources/invalid/distributionsInRangesDocker.groovy
  component-resolver-core/src/test/resources/invalid/duplicatedDocker.groovy
  components-registry-service-client/src/test/kotlin/org/octopusden/octopus/components/registry/client/ComponentRegistryServiceClientTest.kt
  test-common/src/test/resources/components-registry/common/TestComponents.groovy
  test-common/src/test/resources/expected-data/jira-component-version-ranges.json
Labels: enhancement
